// =====================================================
//  site_data.h  -  READS "about-me.txt" (everything about YOU)
//  You do NOT edit this file to change your information.
//  Open  about-me.txt  in the main folder, change it,
//  then run the build program again (see README.md).
//
//  This file also has the small text tools that the
//  project loader (projects/project_loader.h) uses too.
// =====================================================
#pragma once
#include <string>
#include <vector>
#include <map>
#include <fstream>
#include <iostream>
#include <cctype>
#include <ctime>
using namespace std;

// ---------- small text tools ----------

// remove spaces at the start and the end of a text
inline string trim(const string& s) {
    size_t a = 0, b = s.size();
    while (a < b && isspace((unsigned char)s[a])) a++;
    while (b > a && isspace((unsigned char)s[b - 1])) b--;
    return s.substr(a, b - a);
}

inline string lowerText(string s) {
    for (char& c : s) c = (char)tolower((unsigned char)c);
    return s;
}

inline bool endsWith(const string& s, const string& end) {
    return s.size() >= end.size() && s.compare(s.size() - end.size(), end.size(), end) == 0;
}

inline string replaceAll(string text, const string& from, const string& to) {
    size_t pos = 0;
    while ((pos = text.find(from, pos)) != string::npos) {
        text.replace(pos, from.size(), to);
        pos += to.size();
    }
    return text;
}

// cut a text at every "sep". The last part keeps the rest of the text,
// so a text can safely contain more separators than "limit".
inline vector<string> splitLimit(const string& text, char sep, int limit) {
    vector<string> parts;
    string cur;
    for (size_t i = 0; i < text.size(); i++) {
        if (text[i] == sep && (int)parts.size() < limit - 1) {
            parts.push_back(trim(cur));
            cur.clear();
        } else {
            cur += text[i];
        }
    }
    parts.push_back(trim(cur));
    return parts;
}

// make a text safe for HTML. Things like &amp; or &copy; that are already
// written correctly are kept, so "R&D" and "R&amp;D" both work.
inline string toHtml(const string& s) {
    string out;
    for (size_t i = 0; i < s.size(); i++) {
        char c = s[i];
        if (c == '&') {
            size_t j = i + 1;
            while (j < s.size() && (isalnum((unsigned char)s[j]) || s[j] == '#')) j++;
            if (j < s.size() && s[j] == ';' && j > i + 1) out += "&";
            else out += "&amp;";
        } else if (c == '<') out += "&lt;";
        else if (c == '>') out += "&gt;";
        else if (c == '"') out += "&quot;";
        else out += c;
    }
    return out;
}

// ---------- reading a simple text file ----------
// Format (the same for about-me.txt and every file in the projects folder):
//   key: value          lines at the top of the file
//   [section name]      starts a list
//   one item per line   inside a section
//   # comment           ignored, and empty lines are ignored too
struct TextFile {
    map<string, string> keys;
    map<string, vector<string>> sections;

    string get(const string& key, const string& fallback = "") const {
        auto it = keys.find(key);
        if (it == keys.end() || it->second.empty()) return fallback;
        return it->second;
    }
    const vector<string>& list(const string& name) const {
        static const vector<string> none;
        auto it = sections.find(name);
        return it == sections.end() ? none : it->second;
    }
};

inline bool parseTextFile(const string& path, TextFile& out) {
    ifstream file(path, ios::binary);
    if (!file) return false;
    string line, section;
    bool inSection = false, first = true;
    while (getline(file, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (first && line.size() >= 3 && (unsigned char)line[0] == 0xEF
            && (unsigned char)line[1] == 0xBB && (unsigned char)line[2] == 0xBF) line.erase(0, 3);
        first = false;

        string t = trim(line);
        if (t.empty() || t[0] == '#') continue;

        if (t.front() == '[' && t.back() == ']') {
            section = lowerText(trim(t.substr(1, t.size() - 2)));
            inSection = true;
            out.sections[section];       // make sure the section exists
            continue;
        }
        if (inSection) {
            out.sections[section].push_back(t);
        } else {
            size_t colon = t.find(':');
            if (colon == string::npos) {
                cout << "  WARNING: line ignored in " << path << " (no colon): " << t << endl;
                continue;
            }
            out.keys[lowerText(trim(t.substr(0, colon)))] = trim(t.substr(colon + 1));
        }
    }
    return true;
}

// ---------- the information about you (filled by loadAboutMe) ----------
inline string SITE_NAME, FULL_NAME, ROLE, TAGLINE, BADGE, EMAIL, PHONE, LINKEDIN, LOCATION;
inline string UNIVERSITY, UNI_SHORT, FIELD_SHORT, YEAR, SITE_URL, FOOTER_NOTE;
inline string PROFILE_PHOTO, CV_FILE;

// ONE folder holds every image and the CV (profile photo, project photos, demo image, CV)
const string ASSETS_DIR = "assets";
const string DEMO_IMAGE = "demo.jpg";

// web address of a file inside the assets folder, e.g. assetUrl("profile.jpg") -> "assets/profile.jpg"
inline string assetUrl(const string& file) { return ASSETS_DIR + "/" + file; }

// phone number for a "tel:" link (only digits and the + sign)
inline string telHref() {
    string r;
    for (char c : PHONE) if (isdigit((unsigned char)c) || c == '+') r += c;
    return r;
}

struct Stat       { string value, label; };
struct Interest   { string name, text; };
struct Education  { string school, degree, place, result, year; };
struct Experience { string tag, title, text; };
struct SkillGroup { string title; vector<string> items; };

inline vector<string>     typingWords;
inline vector<string>     aboutParagraphs;
inline vector<Stat>       stats;
inline vector<Interest>   interests;
inline vector<Education>  education;
inline vector<Experience> experiences;
inline vector<SkillGroup> skills;

// reads about-me.txt and fills everything above. Returns false if the file is missing.
inline bool loadAboutMe(const string& path) {
    TextFile t;
    if (!parseTextFile(path, t)) return false;

    auto get = [&](const string& key, const string& fallback) { return toHtml(t.get(key, fallback)); };

    FULL_NAME     = get("full_name", "Your Name");
    SITE_NAME     = get("site_name", FULL_NAME);
    ROLE          = get("role", "Student");
    TAGLINE       = get("tagline", "");
    BADGE         = get("badge", "");
    EMAIL         = get("email", "");
    PHONE         = get("phone", "");
    LINKEDIN      = get("linkedin", "");
    LOCATION      = get("location", "");
    UNIVERSITY    = get("university", "");
    UNI_SHORT     = get("university_short", UNIVERSITY);
    FIELD_SHORT   = get("field_short", "EEE");
    FOOTER_NOTE   = get("footer_note", "");
    SITE_URL      = get("site_url", "");
    PROFILE_PHOTO = get("profile_photo", "profile.jpg");
    CV_FILE       = get("cv_file", "Hriduan_CV.pdf");
    while (!SITE_URL.empty() && SITE_URL.back() == '/') SITE_URL.pop_back();

    // year: write a number, or "auto" to always use the year of the build
    string y = trim(t.get("year", "auto"));
    if (lowerText(y) == "auto") {
        time_t now = time(nullptr);
        y = to_string(1900 + localtime(&now)->tm_year);
    }
    YEAR = toHtml(y);

    typingWords.clear();
    for (const string& s : t.list("typing words")) typingWords.push_back(toHtml(s));
    if (typingWords.empty()) typingWords.push_back(ROLE);

    aboutParagraphs.clear();
    for (const string& s : t.list("about")) aboutParagraphs.push_back(toHtml(s));

    stats.clear();
    for (const string& s : t.list("stats")) {
        vector<string> p = splitLimit(s, '|', 2);
        if (p.size() < 2 || p[0].empty()) { cout << "  WARNING: bad line in [stats]: " << s << endl; continue; }
        stats.push_back({toHtml(p[0]), toHtml(p[1])});
    }

    interests.clear();
    for (const string& s : t.list("interests")) {
        vector<string> p = splitLimit(s, '|', 2);
        if (p.size() < 2 || p[0].empty()) { cout << "  WARNING: bad line in [interests]: " << s << endl; continue; }
        interests.push_back({toHtml(p[0]), toHtml(p[1])});
    }

    education.clear();
    for (const string& s : t.list("education")) {
        vector<string> p = splitLimit(s, '|', 5);
        if (p.size() < 5) { cout << "  WARNING: bad line in [education] (needs 5 parts): " << s << endl; continue; }
        education.push_back({toHtml(p[0]), toHtml(p[1]), toHtml(p[2]), toHtml(p[3]), toHtml(p[4])});
    }

    experiences.clear();
    for (const string& s : t.list("experience")) {
        vector<string> p = splitLimit(s, '|', 3);
        if (p.size() < 3) { cout << "  WARNING: bad line in [experience] (needs 3 parts): " << s << endl; continue; }
        experiences.push_back({toHtml(p[0]), toHtml(p[1]), toHtml(p[2])});
    }

    skills.clear();
    for (const string& s : t.list("skills")) {
        vector<string> p = splitLimit(s, '|', 2);
        if (p.size() < 2 || p[0].empty()) { cout << "  WARNING: bad line in [skills]: " << s << endl; continue; }
        SkillGroup g;
        g.title = toHtml(p[0]);
        for (const string& item : splitLimit(p[1], ',', 1000)) if (!item.empty()) g.items.push_back(toHtml(item));
        skills.push_back(g);
    }
    return true;
}
